### ISSUE TITLE
Needs to generate a new package.json in output dir

### ISSUE THREAD

**Issue by tivac** [tivac/yui-clumper#1]
Should probably `JSON.parse()` existing YUI one from `node_modules`, strip out NPM-specific stuff, & then tweak fields to match some sort of pattern & save into output dir.

**Comment by caridy** [comment]
I think we should write a very very simple template, with the minimum info, and 0 or 1 dependency:
- if `io` is part of the generated pkg, then add:

```
"dependencies": {
        "request": "~2.21.0"
    }
```
- if not, no dependency is needed.

**Comment by tivac** [comment]
IIRC `get` needs request as well.

I'm fine w/ a super-simple template but I want to make sure any copyright or other useful metadata from the (presumably) well-maintained YUI `package.json` is maintained. I dunno that I want to sign up to keep the template synced.

**Comment by caridy** [comment]
the same for the `index.js`, it should be a dummy script that does the `module.exports = require('yui/<name-of-the-module>');` that is represented by the generated pkg, and that should be enough to set up all the dependencies and expose a single `Y`. This will be enough.

I imagine this to work:

```
var yql = require('yui-yql').YQL;
```

**Comment by tivac** [comment]
That part's done, though I admittedly just copied the YUI ones w/o thinking about it too hard.

https://github.com/tivac/yui-clumper/blob/master/lib/module.tmpl

**Comment by caridy** [comment]
perfect. sorry, I didn't get a chance to look at the whole code, will do that this week for sure.
